# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%env(APP_SECRET)%"

    # Configuración de sesión (para el carrito)
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    # HTTP Client para consumir tu API Spring Boot
    http_client:
        scoped_clients:
            google_books.api:
                base_uri: 'https://www.googleapis.com/books/v1/'
                headers:
                    Accept: 'application/json'
                timeout: 30
    # Asset mapper para CSS/JS
    asset_mapper:
        paths:
            - assets/

    # Habilitar ESI y fragmentos (opcional)
    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
